version: "3.3"
services:

  azure-blob-storage:
    image: arafato/azurite
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - data-volume:/opt/azurite/folder

volumes:
  data-volume: